package com.zaozao.dao;

import com.zaozao.dataobject.AdminPermissionDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface AdminPermissionDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_permission
     *
     * @mbg.generated Tue Jan 15 14:12:34 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    int deleteByAdminId(Integer adminId);

    int deleteBySchoolId(Integer schoolId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_permission
     *
     * @mbg.generated Tue Jan 15 14:12:34 CST 2019
     */
    int insert(AdminPermissionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_permission
     *
     * @mbg.generated Tue Jan 15 14:12:34 CST 2019
     */
    int insertSelective(AdminPermissionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_permission
     *
     * @mbg.generated Tue Jan 15 14:12:34 CST 2019
     */
    AdminPermissionDO selectByPrimaryKey(Integer id);
    List<AdminPermissionDO> selectByAdminId(Integer adminId);
    List<AdminPermissionDO> selectBySchoolId(Integer schoolId);
    List<AdminPermissionDO> listPermissionByGivenSchoolIdList(@Param("schoolIdList") List<Integer> schoolIdList);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_permission
     *
     * @mbg.generated Tue Jan 15 14:12:34 CST 2019
     */
    int updateByPrimaryKeySelective(AdminPermissionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_permission
     *
     * @mbg.generated Tue Jan 15 14:12:34 CST 2019
     */
    int updateByPrimaryKey(AdminPermissionDO record);
}
