package com.zaozao.dao;

import com.zaozao.dataobject.AdminInfoDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface AdminInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbg.generated Fri Jan 11 15:46:27 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbg.generated Fri Jan 11 15:46:27 CST 2019
     */
    int insert(AdminInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbg.generated Fri Jan 11 15:46:27 CST 2019
     */
    int insertSelective(AdminInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbg.generated Fri Jan 11 15:46:27 CST 2019
     */
    AdminInfoDO selectByPrimaryKey(Integer id);
    AdminInfoDO selectByAccountName(String accountName);
    List<AdminInfoDO> listAdminInfoDO();
    // 确定返回一个对象时使用
    AdminInfoDO selectByAccountRoleAndId(@Param("accountRole") Byte accountRole,@Param("idList") List<Integer>idList);
    List<AdminInfoDO> selectByAccountRoleListAndIdList(@Param("accountRoleList") List<Byte> accountRoleList,
            @Param("adminIdList") List<Integer>adminIdList);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbg.generated Fri Jan 11 15:46:27 CST 2019
     */
    int updateByPrimaryKeySelective(AdminInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbg.generated Fri Jan 11 15:46:27 CST 2019
     */
    int updateByPrimaryKey(AdminInfoDO record);
}
