package com.zaozao.dao;

import com.zaozao.dataobject.AdminPasswordDO;
import org.springframework.stereotype.Repository;

@Repository
public interface AdminPasswordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_password
     *
     * @mbg.generated Fri Jan 11 15:46:27 CST 2019
     */
    int deleteByPrimaryKey(Integer id);
    int deleteByAdminId(Integer adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_password
     *
     * @mbg.generated Fri Jan 11 15:46:27 CST 2019
     */
    int insert(AdminPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_password
     *
     * @mbg.generated Fri Jan 11 15:46:27 CST 2019
     */
     int insertSelective(AdminPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_password
     *
     * @mbg.generated Fri Jan 11 15:46:27 CST 2019
     */
    AdminPasswordDO selectByPrimaryKey(Integer id);
    AdminPasswordDO selectByAdminId(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_password
     *
     * @mbg.generated Fri Jan 11 15:46:27 CST 2019
     */
    int updateByPrimaryKeySelective(AdminPasswordDO record);
    int updateByAdminIdSelective(AdminPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_password
     *
     * @mbg.generated Fri Jan 11 15:46:27 CST 2019
     */
    int updateByPrimaryKey(AdminPasswordDO record);
}
