package com.zaozao.dao;

import com.zaozao.dataobject.AlipayOrderInfoDO;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface AlipayOrderInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_order_info
     *
     * @mbg.generated Wed Mar 13 16:08:32 CST 2019
     */
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_order_info
     *
     * @mbg.generated Wed Mar 13 16:08:32 CST 2019
     */
    int insert(AlipayOrderInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_order_info
     *
     * @mbg.generated Wed Mar 13 16:08:32 CST 2019
     */
    int insertSelective(AlipayOrderInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_order_info
     *
     * @mbg.generated Wed Mar 13 16:08:32 CST 2019
     */
    AlipayOrderInfoDO selectByPrimaryKey(Integer orderId);
    AlipayOrderInfoDO selectByOutTradeNo(String outTradeNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_order_info
     *
     * @mbg.generated Wed Mar 13 16:08:32 CST 2019
     */
    int updateByPrimaryKeySelective(AlipayOrderInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay_order_info
     *
     * @mbg.generated Wed Mar 13 16:08:32 CST 2019
     */
    int updateByPrimaryKey(AlipayOrderInfoDO record);

    AlipayOrderInfoDO selectByBillIdAndOrderStatus(@Param("billId") Integer billId, @Param("orderStatus")byte orderStatus);
    List<AlipayOrderInfoDO> selectByOrderStatusAndModifyStatus(@Param("orderStatus")byte orderStatus,
            @Param("modifyStatus")byte modifyStatus);
}
