package com.zaozao.dao;

import com.zaozao.dataobject.BillItemDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface BillItemDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_item
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    int deleteByPrimaryKey(Integer id);
    int deleteBySchoolId(Integer schoolId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_item
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    int insert(BillItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_item
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    int insertSelective(BillItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_item
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    BillItemDO selectByPrimaryKey(Integer id);
    List<BillItemDO> listItemBySchool(@Param("schoolId") Integer schoolId, @Param("deleteStatus") String deleteStatus);
    List<BillItemDO> listItemBySchoolDynamic(Map<String, Object> map);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_item
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    int updateByPrimaryKeySelective(BillItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_item
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    int updateByPrimaryKey(BillItemDO record);
}
