package com.zaozao.dao;

import com.zaozao.dataobject.BillAmountPayDO;
import com.zaozao.dataobject.BillDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface BillDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    int deleteByPrimaryKey(Integer id);
    int deleteBySchoolId(Integer schoolId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    int insert(BillDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    int insertSelective(BillDO record);
    int selectAmountByStudentId(@Param("studentId")Integer studentId,@Param("deleteStatus") String deleteStatus);
    Double countBillAmountDynamic(Map<String, Object> map);
    List<BillAmountPayDO> countBillAmountByPayType(Map<String, Object> map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    BillDO selectByPrimaryKey(Integer id);

    List<BillDO> selectByPrimaryKeyList(@Param("idList")List<Integer> idList);

    List<BillDO> listBillBySchoolAndClassAndStudentNo(@Param("schoolId") Integer schoolId,
            @Param("classId") Integer classId, @Param("studentNo") String studentNo,
            @Param("billStatus") Byte billStatus, @Param("deleteStatus") String deleteStatus);
    List<BillDO> listBillBySchoolAndClass(@Param("schoolId") Integer schoolId, @Param("classId") Integer classId,@Param("deleteStatus") String deleteStatus);

    List<BillDO> listBill(String deleteStatus);

    List<BillDO> listBillLike(String deleteStatus);

    List<BillDO> listBillBySchoolIdList(@Param("schoolIdList")List<Integer> schoolIdList,
            @Param("deleteStatus") String deleteStatus);

    List<BillDO> listBillBySchoolIdListLike(@Param("schoolIdList")List<Integer> schoolIdList,
            @Param("deleteStatus") String deleteStatus);

    List<BillDO> listBillBySchoolId(@Param("schoolId")Integer schoolId,@Param("deleteStatus") String deleteStatus);

    List<BillDO> listBillBySchoolIdLike(@Param("schoolId")Integer schoolId,@Param("deleteStatus") String deleteStatus);

    List<BillDO> listBillByClassIdList(@Param("classIdList")List<Integer> classIdList,
            @Param("deleteStatus") String deleteStatus);

    List<BillDO> listBillByStudentId(@Param("studentId")Integer studentId,
            @Param("deleteStatus") String deleteStatus,@Param("billStatus")Byte billStatus);

    List<BillDO> listBillByOpenIdAndBillStatus(@Param("openId")String openId, @Param("deleteStatus") String deleteStatus,
            @Param("billStatus") Byte billStatus);

    List<BillDO> listBillByDynamicQuery(@Param("schoolId") Integer schoolId,
            @Param("gradeNum") Integer gradeNum,@Param("classNum") Integer classNum,
            @Param("studentNo") String studentNo,@Param("studentName") String studentName,
            @Param("createDate") String createDate,@Param("payDate") String payDate,
            @Param("billNum") String billNum,@Param("payType") Byte payType,
            @Param("billStatus") Byte billStatus,@Param("synStatus") Byte synStatus,
            @Param("billName") String billName,@Param("billItemId") Integer billItemId,@Param("deleteStatus") String deleteStatus);

    int selectAmountByStudentAndBillAndItem(@Param("studentNo")String studentNo,@Param("billName")String billName,
            @Param("billItemId")Integer billItemId, @Param("deleteStatus") String deleteStatus);

    BillDO getByStudentAndBillAndItem(@Param("studentNo") String studentNo, @Param("billName") String billName,
            @Param("billItemId") Integer billItemId, @Param("deleteStatus") String deleteStatus);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    int updateByPrimaryKeySelective(BillDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    int updateByPrimaryKey(BillDO record);

    BillDO listBillByOutTradeNo(@Param("outTradeNo")String outTradeNo, @Param("deleteStatus")String deleteStatus);
}
