package com.zaozao.dao;

import com.zaozao.dataobject.ClassDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface ClassDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbg.generated Thu Jan 10 16:15:00 CST 2019
     */
    int deleteByPrimaryKey(Integer id);
    int deleteBySchoolId(Integer schoolId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbg.generated Thu Jan 10 16:15:00 CST 2019
     */
    int insert(ClassDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbg.generated Thu Jan 10 16:15:00 CST 2019
     */
    int insertSelective(ClassDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbg.generated Thu Jan 10 16:15:00 CST 2019
     */
    ClassDO selectByPrimaryKey(Integer id);

    List<ClassDO> listClassBySchoolId(@Param("schoolId") Integer schoolId, @Param("deleteStatus") String deleteStatus);
    List<ClassDO> listClass(String deleteStatus);
    List<ClassDO> listClassByDynamicQuery(Map<String, Object> map);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbg.generated Thu Jan 10 16:15:00 CST 2019
     */
    int updateByPrimaryKeySelective(ClassDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbg.generated Thu Jan 10 16:15:00 CST 2019
     */
    int updateByPrimaryKey(ClassDO record);

    int selectAmountByGradeAndClassAndSchoolId(@Param("gradeNum") Integer gradeNum, @Param("classNum") Integer classNum,
            @Param("schoolId") Integer schoolId, @Param("deleteStatus") String deleteStatus);

    int updateByClassAndSchoolSelective(ClassDO record);
    List<ClassDO> selectWhenGraduate(@Param("schoolId") Integer schoolId,@Param("gradeNum") Integer gradeNum, @Param("deleteStatus") String deleteStatus);
    List<ClassDO> selectWhenUpgrade(@Param("schoolId") Integer schoolId,@Param("gradeNum") Integer gradeNum, @Param("deleteStatus") String deleteStatus);

    List<ClassDO> listClassBySchoolIds(@Param("schoolIds")List<Integer> schoolIds, @Param("deleteStatus")String deleteStatus);
}
