package com.zaozao.dao;

import com.zaozao.dataobject.IsvAlipayInfoDO;
import com.zaozao.dataobject.IsvAlipayInfoDOWithBLOBs;
import org.springframework.stereotype.Repository;

@Repository
public interface IsvAlipayInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table isv_alipay_info
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table isv_alipay_info
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    int insert(IsvAlipayInfoDOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table isv_alipay_info
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    int insertSelective(IsvAlipayInfoDOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table isv_alipay_info
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    IsvAlipayInfoDOWithBLOBs selectByPrimaryKey(Integer id);
    IsvAlipayInfoDOWithBLOBs selectByIsvId(Integer isvId);
    IsvAlipayInfoDOWithBLOBs selectByAppIdApplet(String appIdApplet);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table isv_alipay_info
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    int updateByPrimaryKeySelective(IsvAlipayInfoDOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table isv_alipay_info
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(IsvAlipayInfoDOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table isv_alipay_info
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    int updateByPrimaryKey(IsvAlipayInfoDO record);
}
