package com.zaozao.dao;

import com.zaozao.dataobject.IsvDO;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface IsvDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table isv
     *
     * @mbg.generated Mon Jan 14 14:09:16 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table isv
     *
     * @mbg.generated Mon Jan 14 14:09:16 CST 2019
     */
    int insert(IsvDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table isv
     *
     * @mbg.generated Mon Jan 14 14:09:16 CST 2019
     */
    int insertSelective(IsvDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table isv
     *
     * @mbg.generated Mon Jan 14 14:09:16 CST 2019
     */
    IsvDO selectByPrimaryKey(Integer id);
    List<IsvDO> listIsv();
    IsvDO selectByAdminId(Integer adminId);
    int countIsvByAdminId(Integer adminId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table isv
     *
     * @mbg.generated Mon Jan 14 14:09:16 CST 2019
     */
    int updateByPrimaryKeySelective(IsvDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table isv
     *
     * @mbg.generated Mon Jan 14 14:09:16 CST 2019
     */
    int updateByPrimaryKey(IsvDO record);
}
