package com.zaozao.dao;

import com.zaozao.dataobject.IsvWechatInfoDO;
import org.springframework.stereotype.Repository;

@Repository
public interface IsvWechatInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table isv_wechat_info
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table isv_wechat_info
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    int insert(IsvWechatInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table isv_wechat_info
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    int insertSelective(IsvWechatInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table isv_wechat_info
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    IsvWechatInfoDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table isv_wechat_info
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    int updateByPrimaryKeySelective(IsvWechatInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table isv_wechat_info
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    int updateByPrimaryKey(IsvWechatInfoDO record);

    IsvWechatInfoDO selectByIsvId(Integer isvId);

    IsvWechatInfoDO selectByAppIdApplet(String appIdApplet);
}
