package com.zaozao.dao;

import com.zaozao.dataobject.SchoolDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface SchoolDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    int insert(SchoolDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    int insertSelective(SchoolDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    SchoolDO selectByPrimaryKey(Integer id);
    List<SchoolDO> listSchool();
    List<SchoolDO> listSchoolByIsvId(Integer isvId);
    List<SchoolDO> listSchoolByGivenIdList(@Param("schoolIdList") List<Integer> schoolIdList);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    int updateByPrimaryKeySelective(SchoolDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    int updateByPrimaryKey(SchoolDO record);
}
