package com.zaozao.dao;

import com.zaozao.dataobject.WechatOrderInfoDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface WechatOrderInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    int deleteByPrimaryKey(Long orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    int insert(WechatOrderInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    int insertSelective(WechatOrderInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    WechatOrderInfoDO selectByPrimaryKey(Long orderId);

    WechatOrderInfoDO selectByOutTradeNo(String outTradeNo);

    WechatOrderInfoDO selectByBillAndOpenIdExist(@Param("billId")Integer billId,@Param("openId")String openId,
            @Param("orderStatus")Byte orderStatus,
            @Param("payStatus")Byte payStatus);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    int updateByPrimaryKeySelective(WechatOrderInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    int updateByPrimaryKey(WechatOrderInfoDO record);
}
