package com.zaozao.dataobject;

import java.util.Date;

public class AdminInfoDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_info.id
     *
     * @mbg.generated Fri Jan 11 15:46:27 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_info.account_name
     *
     * @mbg.generated Fri Jan 11 15:46:27 CST 2019
     */
    private String accountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_info.account_role
     *
     * @mbg.generated Fri Jan 11 15:46:27 CST 2019
     */
    private Byte accountRole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_info.company_name
     *
     * @mbg.generated Fri Jan 11 15:46:27 CST 2019
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_info.register_date
     *
     * @mbg.generated Fri Jan 11 15:46:27 CST 2019
     */
    private Date registerDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_info.id
     *
     * @return the value of admin_info.id
     *
     * @mbg.generated Fri Jan 11 15:46:27 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_info.id
     *
     * @param id the value for admin_info.id
     *
     * @mbg.generated Fri Jan 11 15:46:27 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_info.account_name
     *
     * @return the value of admin_info.account_name
     *
     * @mbg.generated Fri Jan 11 15:46:27 CST 2019
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_info.account_name
     *
     * @param accountName the value for admin_info.account_name
     *
     * @mbg.generated Fri Jan 11 15:46:27 CST 2019
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_info.account_role
     *
     * @return the value of admin_info.account_role
     *
     * @mbg.generated Fri Jan 11 15:46:27 CST 2019
     */
    public Byte getAccountRole() {
        return accountRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_info.account_role
     *
     * @param accountRole the value for admin_info.account_role
     *
     * @mbg.generated Fri Jan 11 15:46:27 CST 2019
     */
    public void setAccountRole(Byte accountRole) {
        this.accountRole = accountRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_info.company_name
     *
     * @return the value of admin_info.company_name
     *
     * @mbg.generated Fri Jan 11 15:46:27 CST 2019
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_info.company_name
     *
     * @param companyName the value for admin_info.company_name
     *
     * @mbg.generated Fri Jan 11 15:46:27 CST 2019
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_info.register_date
     *
     * @return the value of admin_info.register_date
     *
     * @mbg.generated Fri Jan 11 15:46:27 CST 2019
     */
    public Date getRegisterDate() {
        return registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_info.register_date
     *
     * @param registerDate the value for admin_info.register_date
     *
     * @mbg.generated Fri Jan 11 15:46:27 CST 2019
     */
    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }
}