package com.zaozao.dataobject;

import java.util.Date;

public class AlipayOrderInfoDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_order_info.order_id
     *
     * @mbg.generated Wed Mar 13 16:08:32 CST 2019
     */
    private Integer orderId;

    private Byte orderStatus;
    private Byte modifyStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_order_info.bill_id
     *
     * @mbg.generated Wed Mar 13 16:08:32 CST 2019
     */
    private Integer billId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_order_info.out_trade_no
     *
     * @mbg.generated Wed Mar 13 16:08:32 CST 2019
     */
    private String outTradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_order_info.order_no
     *
     * @mbg.generated Wed Mar 13 16:08:32 CST 2019
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_order_info.trade_no
     *
     * @mbg.generated Wed Mar 13 16:08:32 CST 2019
     */
    private String tradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_order_info.bill_amount
     *
     * @mbg.generated Wed Mar 13 16:08:32 CST 2019
     */
    private Double billAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_order_info.order_amount
     *
     * @mbg.generated Wed Mar 13 16:08:32 CST 2019
     */
    private Double orderAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_order_info.send_date
     *
     * @mbg.generated Wed Mar 13 16:08:32 CST 2019
     */
    private Date sendDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_order_info.end_date
     *
     * @mbg.generated Wed Mar 13 16:08:32 CST 2019
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_order_info.pay_date
     *
     * @mbg.generated Wed Mar 13 16:08:32 CST 2019
     */
    private Date payDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_order_info.buyer_id
     *
     * @mbg.generated Wed Mar 13 16:08:32 CST 2019
     */
    private String buyerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay_order_info.seller_id
     *
     * @mbg.generated Wed Mar 13 16:08:32 CST 2019
     */
    private String sellerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_order_info.order_id
     *
     * @return the value of alipay_order_info.order_id
     * @mbg.generated Wed Mar 13 16:08:32 CST 2019
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_order_info.order_id
     *
     * @param orderId the value for alipay_order_info.order_id
     * @mbg.generated Wed Mar 13 16:08:32 CST 2019
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_order_info.bill_id
     *
     * @return the value of alipay_order_info.bill_id
     * @mbg.generated Wed Mar 13 16:08:32 CST 2019
     */
    public Integer getBillId() {
        return billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_order_info.bill_id
     *
     * @param billId the value for alipay_order_info.bill_id
     * @mbg.generated Wed Mar 13 16:08:32 CST 2019
     */
    public void setBillId(Integer billId) {
        this.billId = billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_order_info.out_trade_no
     *
     * @return the value of alipay_order_info.out_trade_no
     * @mbg.generated Wed Mar 13 16:08:32 CST 2019
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_order_info.out_trade_no
     *
     * @param outTradeNo the value for alipay_order_info.out_trade_no
     * @mbg.generated Wed Mar 13 16:08:32 CST 2019
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_order_info.order_no
     *
     * @return the value of alipay_order_info.order_no
     * @mbg.generated Wed Mar 13 16:08:32 CST 2019
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_order_info.order_no
     *
     * @param orderNo the value for alipay_order_info.order_no
     * @mbg.generated Wed Mar 13 16:08:32 CST 2019
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_order_info.trade_no
     *
     * @return the value of alipay_order_info.trade_no
     * @mbg.generated Wed Mar 13 16:08:32 CST 2019
     */
    public String getTradeNo() {
        return tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_order_info.trade_no
     *
     * @param tradeNo the value for alipay_order_info.trade_no
     * @mbg.generated Wed Mar 13 16:08:32 CST 2019
     */
    public void setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo == null ? null : tradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_order_info.bill_amount
     *
     * @return the value of alipay_order_info.bill_amount
     * @mbg.generated Wed Mar 13 16:08:32 CST 2019
     */
    public Double getBillAmount() {
        return billAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_order_info.bill_amount
     *
     * @param billAmount the value for alipay_order_info.bill_amount
     * @mbg.generated Wed Mar 13 16:08:32 CST 2019
     */
    public void setBillAmount(Double billAmount) {
        this.billAmount = billAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_order_info.order_amount
     *
     * @return the value of alipay_order_info.order_amount
     * @mbg.generated Wed Mar 13 16:08:32 CST 2019
     */
    public Double getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_order_info.order_amount
     *
     * @param orderAmount the value for alipay_order_info.order_amount
     * @mbg.generated Wed Mar 13 16:08:32 CST 2019
     */
    public void setOrderAmount(Double orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_order_info.send_date
     *
     * @return the value of alipay_order_info.send_date
     * @mbg.generated Wed Mar 13 16:08:32 CST 2019
     */
    public Date getSendDate() {
        return sendDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_order_info.send_date
     *
     * @param sendDate the value for alipay_order_info.send_date
     * @mbg.generated Wed Mar 13 16:08:32 CST 2019
     */
    public void setSendDate(Date sendDate) {
        this.sendDate = sendDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_order_info.end_date
     *
     * @return the value of alipay_order_info.end_date
     * @mbg.generated Wed Mar 13 16:08:32 CST 2019
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_order_info.end_date
     *
     * @param endDate the value for alipay_order_info.end_date
     * @mbg.generated Wed Mar 13 16:08:32 CST 2019
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_order_info.pay_date
     *
     * @return the value of alipay_order_info.pay_date
     * @mbg.generated Wed Mar 13 16:08:32 CST 2019
     */
    public Date getPayDate() {
        return payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_order_info.pay_date
     *
     * @param payDate the value for alipay_order_info.pay_date
     * @mbg.generated Wed Mar 13 16:08:32 CST 2019
     */
    public void setPayDate(Date payDate) {
        this.payDate = payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_order_info.buyer_id
     *
     * @return the value of alipay_order_info.buyer_id
     * @mbg.generated Wed Mar 13 16:08:32 CST 2019
     */
    public String getBuyerId() {
        return buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_order_info.buyer_id
     *
     * @param buyerId the value for alipay_order_info.buyer_id
     * @mbg.generated Wed Mar 13 16:08:32 CST 2019
     */
    public void setBuyerId(String buyerId) {
        this.buyerId = buyerId == null ? null : buyerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alipay_order_info.seller_id
     *
     * @return the value of alipay_order_info.seller_id
     * @mbg.generated Wed Mar 13 16:08:32 CST 2019
     */
    public String getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alipay_order_info.seller_id
     *
     * @param sellerId the value for alipay_order_info.seller_id
     * @mbg.generated Wed Mar 13 16:08:32 CST 2019
     */
    public void setSellerId(String sellerId) {
        this.sellerId = sellerId == null ? null : sellerId.trim();
    }

    public Byte getOrderStatus() {
        return orderStatus;
    }

    public void setOrderStatus(Byte orderStatus) {
        this.orderStatus = orderStatus;
    }

    public Byte getModifyStatus() {
        return modifyStatus;
    }

    public void setModifyStatus(Byte modifyStatus) {
        this.modifyStatus = modifyStatus;
    }
}
