package com.zaozao.dataobject;

public class BillItemDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_item.id
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_item.item_name
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    private String itemName;

    private Integer schoolId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_item.id
     *
     * @return the value of bill_item.id
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_item.id
     *
     * @param id the value for bill_item.id
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_item.item_name
     *
     * @return the value of bill_item.item_name
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    public String getItemName() {
        return itemName;
    }

    private String deleteStatus;
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_item.item_name
     *
     * @param itemName the value for bill_item.item_name
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    public Integer getSchoolId() {
        return schoolId;
    }

    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    public String getDeleteStatus() {
        return deleteStatus;
    }

    public void setDeleteStatus(String deleteStatus) {
        this.deleteStatus = deleteStatus;
    }
}
