package com.zaozao.dataobject;

import java.util.Date;

public class BillDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.id
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    private Integer id;
    private Integer isvId;
    private Integer schoolId;
    private String schoolName;
    private Integer classId;
    private Integer gradeNum;
    private Integer classNum;
    private String studentName;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.student_id
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    private String studentIdentity;
    private String studentNo;
    private Integer studentId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.bill_name
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    private String billName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.bill_item_id
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    private Integer billItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.bill_amount
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    private Double billAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.bill_status
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    private Byte billStatus;
    private Byte synStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.pay_type
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    private Byte payType;

    private String serialNum;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.comment
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    private String billNum;

    private Date createDate;
    private Date payDate;
    private Date updateDate;
    private Date endDate;

    private String comment;
    private String deleteStatus;
    private String wechatOpenId;
    private String outTradeNo;

    public String getBillNum() {
        return billNum;
    }

    public void setBillNum(String billNum) {
        this.billNum = billNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.id
     *
     * @return the value of bill.id
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.id
     *
     * @param id the value for bill.id
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.student_id
     *
     * @return the value of bill.student_id
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    public String getStudentNo() {
        return studentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.student_id
     *
     * @param studentNo the value for bill.student_id
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    public void setStudentNo(String studentNo) {
        this.studentNo = studentNo == null ? null : studentNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.bill_name
     *
     * @return the value of bill.bill_name
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    public String getBillName() {
        return billName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.bill_name
     *
     * @param billName the value for bill.bill_name
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    public void setBillName(String billName) {
        this.billName = billName == null ? null : billName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.bill_item_id
     *
     * @return the value of bill.bill_item_id
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    public Integer getBillItemId() {
        return billItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.bill_item_id
     *
     * @param billItemId the value for bill.bill_item_id
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    public void setBillItemId(Integer billItemId) {
        this.billItemId = billItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.bill_amount
     *
     * @return the value of bill.bill_amount
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    public Double getBillAmount() {
        return billAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.bill_amount
     *
     * @param billAmount the value for bill.bill_amount
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    public void setBillAmount(Double billAmount) {
        this.billAmount = billAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.bill_status
     *
     * @return the value of bill.bill_status
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    public Byte getBillStatus() {
        return billStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.bill_status
     *
     * @param billStatus the value for bill.bill_status
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    public void setBillStatus(Byte billStatus) {
        this.billStatus = billStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.pay_type
     *
     * @return the value of bill.pay_type
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    public Byte getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.pay_type
     *
     * @param payType the value for bill.pay_type
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    public void setPayType(Byte payType) {
        this.payType = payType;
    }

    public Integer getClassNum() {
        return classNum;
    }

    public void setClassNum(Integer classNum) {
        this.classNum = classNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.comment
     *
     * @return the value of bill.comment
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.comment
     *
     * @param comment the value for bill.comment
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    public Integer getSchoolId() {
        return schoolId;
    }

    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    public Integer getClassId() {
        return classId;
    }

    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    public String getStudentName() {
        return studentName;
    }

    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }

    public String getSchoolName() {
        return schoolName;
    }

    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName;
    }

    public Integer getGradeNum() {
        return gradeNum;
    }

    public void setGradeNum(Integer gradeNum) {
        this.gradeNum = gradeNum;
    }

    public String getSerialNum() {
        return serialNum;
    }

    public void setSerialNum(String serialNum) {
        this.serialNum = serialNum;
    }

    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public Date getPayDate() {
        return payDate;
    }

    public void setPayDate(Date payDate) {
        this.payDate = payDate;
    }

    public Date getUpdateDate() {
        return updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    public String getDeleteStatus() {
        return deleteStatus;
    }

    public void setDeleteStatus(String deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    public Integer getStudentId() {
        return studentId;
    }

    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    public String getWechatOpenId() {
        return wechatOpenId;
    }

    public void setWechatOpenId(String wechatOpenId) {
        this.wechatOpenId = wechatOpenId;
    }

    public String getOutTradeNo() {
        return outTradeNo;
    }

    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo;
    }

    public Integer getIsvId() {
        return isvId;
    }

    public void setIsvId(Integer isvId) {
        this.isvId = isvId;
    }

    public String getStudentIdentity() {
        return studentIdentity;
    }

    public void setStudentIdentity(String studentIdentity) {
        this.studentIdentity = studentIdentity;
    }

    public Byte getSynStatus() {
        return synStatus;
    }

    public void setSynStatus(Byte synStatus) {
        this.synStatus = synStatus;
    }

    public Date getEndDate() {
        return endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    @Override
    public String toString() {
        return "BillDO{" + "id=" + id + ", schoolId=" + schoolId + ", schoolName='" + schoolName + '\'' + ", classId="
                + classId + ", gradeNum=" + gradeNum + ", classNum=" + classNum + ", studentName='" + studentName + '\''
                + ", studentNo='" + studentNo + '\'' + ", studentId=" + studentId + ", billName='" + billName + '\''
                + ", billItemId=" + billItemId + ", billAmount=" + billAmount + ", billStatus=" + billStatus
                + ", payType=" + payType + ", serialNum='" + serialNum + '\'' + ", billNum='" + billNum + '\''
                + ", createDate=" + createDate + ", payDate=" + payDate + ", updateDate=" + updateDate + ", comment='"
                + comment + '\'' + ", deleteStatus='" + deleteStatus + '\'' + ", wechatOpenId='" + wechatOpenId + '\''
                + ", outTradeNo='" + outTradeNo + '\'' + '}';
    }
}
