package com.zaozao.dataobject;

public class ClassDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.id
     *
     * @mbg.generated Thu Jan 10 16:15:00 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.class_name
     *
     * @mbg.generated Thu Jan 10 16:15:00 CST 2019
     */

    private Integer gradeNum;
    private Integer classNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.school_id
     *
     * @mbg.generated Thu Jan 10 16:15:00 CST 2019
     */
    private Integer schoolId;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.head_teacher_name
     *
     * @mbg.generated Thu Jan 10 16:15:00 CST 2019
     */
    private String headTeacherName;
    private String deleteStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.id
     *
     * @return the value of class.id
     *
     * @mbg.generated Thu Jan 10 16:15:00 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.id
     *
     * @param id the value for class.id
     *
     * @mbg.generated Thu Jan 10 16:15:00 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getGradeNum() {
        return gradeNum;
    }

    public void setGradeNum(Integer gradeNum) {
        this.gradeNum = gradeNum;
    }

    public Integer getClassNum() {
        return classNum;
    }

    public void setClassNum(Integer classNum) {
        this.classNum = classNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.school_id
     *
     * @return the value of class.school_id
     *
     * @mbg.generated Thu Jan 10 16:15:00 CST 2019
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.school_id
     *
     * @param schoolId the value for class.school_id
     *
     * @mbg.generated Thu Jan 10 16:15:00 CST 2019
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.head_teacher_name
     *
     * @return the value of class.head_teacher_name
     *
     * @mbg.generated Thu Jan 10 16:15:00 CST 2019
     */
    public String getHeadTeacherName() {
        return headTeacherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.head_teacher_name
     *
     * @param headTeacherName the value for class.head_teacher_name
     *
     * @mbg.generated Thu Jan 10 16:15:00 CST 2019
     */
    public void setHeadTeacherName(String headTeacherName) {
        this.headTeacherName = headTeacherName == null ? null : headTeacherName.trim();
    }

    public String getDeleteStatus() {
        return deleteStatus;
    }

    public void setDeleteStatus(String deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    @Override
    public String toString() {
        return "ClassDO{" + "id=" + id + ", gradeNum=" + gradeNum + ", classNum=" + classNum + ", schoolId=" + schoolId
                + ", headTeacherName='" + headTeacherName + '\'' + '}';
    }
}
