package com.zaozao.dataobject;

public class IsvAlipayInfoDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column isv_alipay_info.id
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column isv_alipay_info.isv_id
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    private Integer isvId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column isv_alipay_info.isv_pid
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    private String isvPid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column isv_alipay_info.app_id_applet
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    private String appIdApplet;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column isv_alipay_info.id
     *
     * @return the value of isv_alipay_info.id
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column isv_alipay_info.id
     *
     * @param id the value for isv_alipay_info.id
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column isv_alipay_info.isv_id
     *
     * @return the value of isv_alipay_info.isv_id
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    public Integer getIsvId() {
        return isvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column isv_alipay_info.isv_id
     *
     * @param isvId the value for isv_alipay_info.isv_id
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    public void setIsvId(Integer isvId) {
        this.isvId = isvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column isv_alipay_info.isv_pid
     *
     * @return the value of isv_alipay_info.isv_pid
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    public String getIsvPid() {
        return isvPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column isv_alipay_info.isv_pid
     *
     * @param isvPid the value for isv_alipay_info.isv_pid
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    public void setIsvPid(String isvPid) {
        this.isvPid = isvPid == null ? null : isvPid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column isv_alipay_info.app_id_applet
     *
     * @return the value of isv_alipay_info.app_id_applet
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    public String getAppIdApplet() {
        return appIdApplet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column isv_alipay_info.app_id_applet
     *
     * @param appIdApplet the value for isv_alipay_info.app_id_applet
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    public void setAppIdApplet(String appIdApplet) {
        this.appIdApplet = appIdApplet == null ? null : appIdApplet.trim();
    }
}