package com.zaozao.dataobject;

public class IsvAlipayInfoDOWithBLOBs extends IsvAlipayInfoDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column isv_alipay_info.app_public_key
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    private String appPublicKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column isv_alipay_info.app_private_key
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    private String appPrivateKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column isv_alipay_info.alipay_public_key
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    private String alipayPublicKey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column isv_alipay_info.app_public_key
     *
     * @return the value of isv_alipay_info.app_public_key
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    public String getAppPublicKey() {
        return appPublicKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column isv_alipay_info.app_public_key
     *
     * @param appPublicKey the value for isv_alipay_info.app_public_key
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    public void setAppPublicKey(String appPublicKey) {
        this.appPublicKey = appPublicKey == null ? null : appPublicKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column isv_alipay_info.app_private_key
     *
     * @return the value of isv_alipay_info.app_private_key
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    public String getAppPrivateKey() {
        return appPrivateKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column isv_alipay_info.app_private_key
     *
     * @param appPrivateKey the value for isv_alipay_info.app_private_key
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    public void setAppPrivateKey(String appPrivateKey) {
        this.appPrivateKey = appPrivateKey == null ? null : appPrivateKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column isv_alipay_info.alipay_public_key
     *
     * @return the value of isv_alipay_info.alipay_public_key
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    public String getAlipayPublicKey() {
        return alipayPublicKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column isv_alipay_info.alipay_public_key
     *
     * @param alipayPublicKey the value for isv_alipay_info.alipay_public_key
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    public void setAlipayPublicKey(String alipayPublicKey) {
        this.alipayPublicKey = alipayPublicKey == null ? null : alipayPublicKey.trim();
    }
}