package com.zaozao.dataobject;

public class IsvDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column isv.id
     *
     * @mbg.generated Mon Jan 14 14:09:16 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column isv.company_name
     *
     * @mbg.generated Mon Jan 14 14:09:16 CST 2019
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column isv.company_address
     *
     * @mbg.generated Mon Jan 14 14:09:16 CST 2019
     */
    private String companyAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column isv.company_contact
     *
     * @mbg.generated Mon Jan 14 14:09:16 CST 2019
     */
    private String companyContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column isv.alipay_account
     *
     * @mbg.generated Mon Jan 14 14:09:16 CST 2019
     */
    private String companyTel;

    private Integer adminId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column isv.id
     *
     * @return the value of isv.id
     * @mbg.generated Mon Jan 14 14:09:16 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column isv.id
     *
     * @param id the value for isv.id
     * @mbg.generated Mon Jan 14 14:09:16 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column isv.company_name
     *
     * @return the value of isv.company_name
     * @mbg.generated Mon Jan 14 14:09:16 CST 2019
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column isv.company_name
     *
     * @param companyName the value for isv.company_name
     * @mbg.generated Mon Jan 14 14:09:16 CST 2019
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column isv.company_address
     *
     * @return the value of isv.company_address
     * @mbg.generated Mon Jan 14 14:09:16 CST 2019
     */
    public String getCompanyAddress() {
        return companyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column isv.company_address
     *
     * @param companyAddress the value for isv.company_address
     * @mbg.generated Mon Jan 14 14:09:16 CST 2019
     */
    public void setCompanyAddress(String companyAddress) {
        this.companyAddress = companyAddress == null ? null : companyAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column isv.company_contact
     *
     * @return the value of isv.company_contact
     * @mbg.generated Mon Jan 14 14:09:16 CST 2019
     */
    public String getCompanyContact() {
        return companyContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column isv.company_contact
     *
     * @param companyContact the value for isv.company_contact
     * @mbg.generated Mon Jan 14 14:09:16 CST 2019
     */
    public void setCompanyContact(String companyContact) {
        this.companyContact = companyContact == null ? null : companyContact.trim();
    }

    public String getCompanyTel() {
        return companyTel;
    }

    public void setCompanyTel(String companyTel) {
        this.companyTel = companyTel;
    }

    public Integer getAdminId() {
        return adminId;
    }

    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }
}
