package com.zaozao.dataobject;

public class IsvWechatInfoDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column isv_wechat_info.id
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column isv_wechat_info.isv_id
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    private Integer isvId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column isv_wechat_info.mch_id
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    private String mchId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column isv_wechat_info.app_id_official_account
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    private String appIdOfficialAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column isv_wechat_info.app_secret_official_account
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    private String appSecretOfficialAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column isv_wechat_info.app_id_applet
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    private String appIdApplet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column isv_wechat_info.app_secret_applet
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    private String appSecretApplet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column isv_wechat_info.mch_key
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    private String mchKey;
    private String notifyUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column isv_wechat_info.id
     *
     * @return the value of isv_wechat_info.id
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column isv_wechat_info.id
     *
     * @param id the value for isv_wechat_info.id
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column isv_wechat_info.isv_id
     *
     * @return the value of isv_wechat_info.isv_id
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    public Integer getIsvId() {
        return isvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column isv_wechat_info.isv_id
     *
     * @param isvId the value for isv_wechat_info.isv_id
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    public void setIsvId(Integer isvId) {
        this.isvId = isvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column isv_wechat_info.mch_id
     *
     * @return the value of isv_wechat_info.mch_id
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    public String getMchId() {
        return mchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column isv_wechat_info.mch_id
     *
     * @param mchId the value for isv_wechat_info.mch_id
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    public void setMchId(String mchId) {
        this.mchId = mchId == null ? null : mchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column isv_wechat_info.app_id_official_account
     *
     * @return the value of isv_wechat_info.app_id_official_account
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    public String getAppIdOfficialAccount() {
        return appIdOfficialAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column isv_wechat_info.app_id_official_account
     *
     * @param appIdOfficialAccount the value for isv_wechat_info.app_id_official_account
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    public void setAppIdOfficialAccount(String appIdOfficialAccount) {
        this.appIdOfficialAccount = appIdOfficialAccount == null ? null : appIdOfficialAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column isv_wechat_info.app_secret_official_account
     *
     * @return the value of isv_wechat_info.app_secret_official_account
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    public String getAppSecretOfficialAccount() {
        return appSecretOfficialAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column isv_wechat_info.app_secret_official_account
     *
     * @param appSecretOfficialAccount the value for isv_wechat_info.app_secret_official_account
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    public void setAppSecretOfficialAccount(String appSecretOfficialAccount) {
        this.appSecretOfficialAccount = appSecretOfficialAccount == null ? null : appSecretOfficialAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column isv_wechat_info.app_id_applet
     *
     * @return the value of isv_wechat_info.app_id_applet
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    public String getAppIdApplet() {
        return appIdApplet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column isv_wechat_info.app_id_applet
     *
     * @param appIdApplet the value for isv_wechat_info.app_id_applet
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    public void setAppIdApplet(String appIdApplet) {
        this.appIdApplet = appIdApplet == null ? null : appIdApplet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column isv_wechat_info.app_secret_applet
     *
     * @return the value of isv_wechat_info.app_secret_applet
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    public String getAppSecretApplet() {
        return appSecretApplet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column isv_wechat_info.app_secret_applet
     *
     * @param appSecretApplet the value for isv_wechat_info.app_secret_applet
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    public void setAppSecretApplet(String appSecretApplet) {
        this.appSecretApplet = appSecretApplet == null ? null : appSecretApplet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column isv_wechat_info.mch_key
     *
     * @return the value of isv_wechat_info.mch_key
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    public String getMchKey() {
        return mchKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column isv_wechat_info.mch_key
     *
     * @param mchKey the value for isv_wechat_info.mch_key
     *
     * @mbg.generated Sat Mar 09 18:06:19 CST 2019
     */
    public void setMchKey(String mchKey) {
        this.mchKey = mchKey == null ? null : mchKey.trim();
    }

    public String getNotifyUrl() {
        return notifyUrl;
    }

    public void setNotifyUrl(String notifyUrl) {
        this.notifyUrl = notifyUrl;
    }
}
