package com.zaozao.dataobject;

import java.io.Serializable;

public class StudentDO  implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.name
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.gender
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    private Byte gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_id
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    private String studentIdentity;
    private String studentNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.class_id
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    private Integer classId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.school_id
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    private Integer schoolId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.parent_phone_num
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    private String parentPhoneNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.parent_name
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    private String parentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.guardian
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    private String guardian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.residence
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    private Byte residence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.school_shuttle
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    private Byte schoolShuttle;
    private String deleteStatus;

    private String wechatOpenId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.id
     *
     * @return the value of student.id
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.id
     *
     * @param id the value for student.id
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.name
     *
     * @return the value of student.name
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.name
     *
     * @param name the value for student.name
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.gender
     *
     * @return the value of student.gender
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.gender
     *
     * @param gender the value for student.gender
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_id
     *
     * @return the value of student.student_id
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    public String getStudentNo() {
        return studentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_id
     *
     * @param studentNo the value for student.student_id
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    public void setStudentNo(String studentNo) {
        this.studentNo = studentNo == null ? null : studentNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.class_id
     *
     * @return the value of student.class_id
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.class_id
     *
     * @param classId the value for student.class_id
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.school_id
     *
     * @return the value of student.school_id
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.school_id
     *
     * @param schoolId the value for student.school_id
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.parent_phone_num
     *
     * @return the value of student.parent_phone_num
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    public String getParentPhoneNum() {
        return parentPhoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.parent_phone_num
     *
     * @param parentPhoneNum the value for student.parent_phone_num
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    public void setParentPhoneNum(String parentPhoneNum) {
        this.parentPhoneNum = parentPhoneNum == null ? null : parentPhoneNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.parent_name
     *
     * @return the value of student.parent_name
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    public String getParentName() {
        return parentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.parent_name
     *
     * @param parentName the value for student.parent_name
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    public void setParentName(String parentName) {
        this.parentName = parentName == null ? null : parentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.guardian
     *
     * @return the value of student.guardian
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    public String getGuardian() {
        return guardian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.guardian
     *
     * @param guardian the value for student.guardian
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    public void setGuardian(String guardian) {
        this.guardian = guardian == null ? null : guardian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.residence
     *
     * @return the value of student.residence
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    public Byte getResidence() {
        return residence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.residence
     *
     * @param residence the value for student.residence
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    public void setResidence(Byte residence) {
        this.residence = residence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.school_shuttle
     *
     * @return the value of student.school_shuttle
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    public Byte getSchoolShuttle() {
        return schoolShuttle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.school_shuttle
     *
     * @param schoolShuttle the value for student.school_shuttle
     *
     * @mbg.generated Thu Jan 10 15:00:21 CST 2019
     */
    public void setSchoolShuttle(Byte schoolShuttle) {
        this.schoolShuttle = schoolShuttle;
    }

    public String getDeleteStatus() {
        return deleteStatus;
    }

    public void setDeleteStatus(String deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    public String getWechatOpenId() {
        return wechatOpenId;
    }

    public void setWechatOpenId(String wechatOpenId) {
        this.wechatOpenId = wechatOpenId;
    }

    public StudentDO(Integer id, String name, Byte gender, String studentNo, Integer classId, Integer schoolId,
            String parentPhoneNum, String parentName, String guardian, Byte residence, Byte schoolShuttle) {
        this.id = id;
        this.name = name;
        this.gender = gender;
        this.studentNo = studentNo;
        this.classId = classId;
        this.schoolId = schoolId;
        this.parentPhoneNum = parentPhoneNum;
        this.parentName = parentName;
        this.guardian = guardian;
        this.residence = residence;
        this.schoolShuttle = schoolShuttle;
    }

    public StudentDO() {
        super();
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }

        StudentDO other = (StudentDO) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                &&(this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
                &&(this.getGender() == null ? other.getGender() == null : this.getGender().equals(other.getGender()))
                &&(this.getStudentNo() == null ? other.getStudentNo() == null :
                this.getStudentNo().equals(other.getStudentNo()))
                &&(this.getClassId() == null ? other.getClassId() == null : this.getClassId().equals(other.getClassId()))
                &&(this.getParentPhoneNum() == null ? other.getParentPhoneNum() == null : this.getParentPhoneNum().equals(other.getParentPhoneNum()))
                &&(this.getParentName() == null ? other.getParentName() == null : this.getParentName().equals(other.getParentName()))
                &&(this.getGuardian() == null ? other.getGuardian() == null : this.getGuardian().equals(other.getGuardian()))
                &&(this.getResidence() == null ? other.getResidence() == null : this.getResidence().equals(other.getResidence()))
                &&(this.getSchoolShuttle() == null ? other.getSchoolShuttle() == null : this.getSchoolShuttle().equals(other.getSchoolShuttle()));
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getGender() == null) ? 0 : getGender().hashCode());
        result = prime * result + ((getStudentNo() == null) ? 0 : getStudentNo().hashCode());
        result = prime * result + ((getClassId() == null) ? 0 : getClassId().hashCode());
        result = prime * result + ((getParentPhoneNum() == null) ? 0 : getParentPhoneNum().hashCode());
        result = prime * result + ((getParentName() == null) ? 0 : getParentName().hashCode());
        result = prime * result + ((getGuardian() == null) ? 0 : getGuardian().hashCode());
        result = prime * result + ((getResidence() == null) ? 0 : getResidence().hashCode());
        result = prime * result + ((getSchoolShuttle() == null) ? 0 : getSchoolShuttle().hashCode());
        return result;
    }

    public String getStudentIdentity() {
        return studentIdentity;
    }

    public void setStudentIdentity(String studentIdentity) {
        this.studentIdentity = studentIdentity;
    }
}
