package com.zaozao.dataobject;

import java.util.Date;

public class WechatOrderInfoDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_id
     *
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.bill_id
     *
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    private Integer billId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.out_trade_no
     *
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    private String outTradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.transaction_id
     *
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    private String transactionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.open_id
     *
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.bill_amount
     *
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    private Double billAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_amount
     *
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    private Double orderAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_status
     *
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    private Byte orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.pay_status
     *
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    private Byte payStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.create_time
     *
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.pay_time
     *
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    private Date payTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.time_expire
     *
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    private Date timeExpire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.prepay_id
     *
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    private String prepayId;

    private String subMchId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_id
     *
     * @return the value of order.order_id
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_id
     *
     * @param orderId the value for order.order_id
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.bill_id
     *
     * @return the value of order.bill_id
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    public Integer getBillId() {
        return billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.bill_id
     *
     * @param billId the value for order.bill_id
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    public void setBillId(Integer billId) {
        this.billId = billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.out_trade_no
     *
     * @return the value of order.out_trade_no
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.out_trade_no
     *
     * @param outTradeNo the value for order.out_trade_no
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.transaction_id
     *
     * @return the value of order.transaction_id
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.transaction_id
     *
     * @param transactionId the value for order.transaction_id
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId == null ? null : transactionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.open_id
     *
     * @return the value of order.open_id
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.open_id
     *
     * @param openId the value for order.open_id
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.bill_amount
     *
     * @return the value of order.bill_amount
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    public Double getBillAmount() {
        return billAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.bill_amount
     *
     * @param billAmount the value for order.bill_amount
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    public void setBillAmount(Double billAmount) {
        this.billAmount = billAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_amount
     *
     * @return the value of order.order_amount
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    public Double getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_amount
     *
     * @param orderAmount the value for order.order_amount
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    public void setOrderAmount(Double orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_status
     *
     * @return the value of order.order_status
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    public Byte getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_status
     *
     * @param orderStatus the value for order.order_status
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    public void setOrderStatus(Byte orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.pay_status
     *
     * @return the value of order.pay_status
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    public Byte getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.pay_status
     *
     * @param payStatus the value for order.pay_status
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    public void setPayStatus(Byte payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.create_time
     *
     * @return the value of order.create_time
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.create_time
     *
     * @param createTime the value for order.create_time
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.pay_time
     *
     * @return the value of order.pay_time
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.pay_time
     *
     * @param payTime the value for order.pay_time
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.time_expire
     *
     * @return the value of order.time_expire
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    public Date getTimeExpire() {
        return timeExpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.time_expire
     *
     * @param timeExpire the value for order.time_expire
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    public void setTimeExpire(Date timeExpire) {
        this.timeExpire = timeExpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.prepay_id
     *
     * @return the value of order.prepay_id
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    public String getPrepayId() {
        return prepayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.prepay_id
     *
     * @param prepayId the value for order.prepay_id
     * @mbg.generated Tue Mar 05 14:22:10 CST 2019
     */
    public void setPrepayId(String prepayId) {
        this.prepayId = prepayId == null ? null : prepayId.trim();
    }

    public String getSubMchId() {
        return subMchId;
    }

    public void setSubMchId(String subMchId) {
        this.subMchId = subMchId;
    }

    @Override
    public String toString() {
        return "WechatOrderInfoDO{" + "orderId=" + orderId + ", billId=" + billId + ", outTradeNo='" + outTradeNo + '\''
                + ", transactionId='" + transactionId + '\'' + ", openId='" + openId + '\'' + ", billAmount="
                + billAmount + ", orderAmount=" + orderAmount + ", orderStatus=" + orderStatus + ", payStatus="
                + payStatus + ", createTime=" + createTime + ", payTime=" + payTime + ", timeExpire=" + timeExpire
                + ", prepayId='" + prepayId + '\'' + ", subMchId='" + subMchId + '\'' + '}';
    }
}
